# Generated by Django 5.0.6 on 2024-05-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycling_store_app.customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
