# Generated by Django 5.0.6 on 2024-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0002_alter_customerorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='part',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='part_in_stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
