# Generated by Django 5.0.6 on 2024-05-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0003_vehicle_part_vehicle_part_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='part',
            new_name='parts',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='part_in_stock',
            new_name='parts_in_stock',
        ),
    ]
