# Generated by Django 5.0.6 on 2024-05-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0004_rename_part_vehicle_parts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='parts_in_stock',
        ),
    ]
