# Generated by Django 5.0.6 on 2024-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0007_color_handlebar_vehicle_color_vehicle_handlebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlebar',
            name='handlebars_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
