# Generated by Django 5.0.6 on 2024-05-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0008_handlebar_handlebars_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycling_store_app.color'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='handlebar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycling_store_app.handlebar'),
        ),
    ]
